### ISSUE TITLE
Publish events only after successful transaction

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey#110]
Hello all

We're looking to use the Guicey Eventbus integration to post events to our AsyncEventBus, however we only want to do so if the transaction that triggered the event successfully committed. 

We are using the `@InTransaction` annotation in our service methods and calling out to a number of `@JdbiRepository` repositories within them to change data in our data layer. At the end of the service, we want to post a successful event "FooCompleted" to the event bus.

Is there a way to tap into the transaction handler that manages `InTransaction` such that after the commit, we can signal a successful event and post any accumulated events to the event bus? How might we do so?

Thanks for any guidance.

**Comment by xvik** [comment]
Hello!

I don't see any api for directly listening transactions in jdbi3 or jdbc. If you want to listen to all transactions I'm afraid your only way is a custom jdbc driver like [p6spy](https://github.com/p6spy/p6spy).

If you need to listen for a couple of methods, then you can simply play with transaction scope:

```java
public class MyService {
      public Something doSmth() {
            Something res = transactionalMethod();
            // publish event here (after transaction)
           return res;
      }

      @InTransaction
      private Something transactionalMethod() {
         // do something in tx
      }
}
```

If you want to listen to all *annotated* transactions, you can apply AOP handler above default transactional handler, so it would apply above transaction:

```java
public class TransactionEventInterceptor implements MethodInterceptor {

@Inject
private UnitManager unit;

@Override
    @SuppressWarnings("PMD.AvoidThrowingRawExceptionTypes")
    public Object invoke(final MethodInvocation invocation) throws Throwable {
        Object res = invocation.proceed();
        if (!manager.isUnitStarted()) {
             // publish event (out of transaction)
            // condition above required to filter inlined handler (annotated method called from annotated method)
        }
        return res;
    }
}
```

Registration in guice module:

```java
TransactionEventInterceptor  interceptor = new  TransactionEventInterceptor()
// inject guice fields 
requestInjection(interceptor); 

bindInterceptor(Matchers.annotatedWith(InTransaction.class), NoSyntheticMatcher.instance(), interceptor);
bindInterceptor(Matchers.any(), Matchers.annotatedWith(InTransaction.class), interceptor);
```

This registration must appear BEFORE jdbi module, so this interceptor execute earlier,
Use [app report](http://xvik.github.io/dropwizard-guicey/5.1.0/guide/diagnostic/aop-report/) to check correct ordder.

Also, you can use your own annotation like `@TxTrackEvent` instead of `@InTrasnaction` to better express where to apply your custom app interceptor:

```java
@TxTrackEvent
@InTransaction
public void myMethod()
```

**Comment by mustafashabib** [comment]
Thank you for the details. 

A couple of questions - what is the best way to control where my interceptor registration takes place? I configure my `GuiceBundle` in my Dropwizard Application like so:

~~~
final GuiceBundle guiceBundle =
        GuiceBundle.builder()
            .printDiagnosticInfo()
            .printLifecyclePhasesDetailed()
            .printGuiceAopMap()
            .enableAutoConfig("my.package")
            .bundles(
                JdbiBundle.<PlannerConfiguration>forDatabase(
                        (conf, env) -> conf.getDataSourceFactory())
                    .withConfig(jdbi -> jdbi.setSqlLogger(new PlannerSqlLogger()))
                    .withPlugins(
                        new KotlinPlugin(),
                        new KotlinSqlObjectPlugin(),
                        new PostgresPlugin(),
                        new VavrPlugin(),
                        new JodaTimePlugin()),
                new EventBusBundle(new AsyncEventBus(new ContextAwareExecutor())))
            .modules(new MyGuiceBundle())
            .build();
~~~

and where `MyGuiceBundle` is:

~~~

public class MyGuiceBundle extends DropwizardAwareModule<MyConfiguration> {

  @Override
  protected void configure() {
    final TransacationalEventInterceptor interceptor = new TransacationalEventInterceptor();
    // inject guice fields
    requestInjection(interceptor);

    bindInterceptor(
        Matchers.annotatedWith(InTransaction.class), NoSyntheticMatcher.instance(), interceptor);
    bindInterceptor(Matchers.any(), Matchers.annotatedWith(InTransaction.class), interceptor);
  }
~~~

Finally, one more question -- in my Services that have `InTransaction` annotations, I'd like to post all of my queued events, as mentioned. To do so, I created a `RequestScoped` class that wraps a `java.util.Queue<>` so that each request has its own queue of events. This is not being injected, properly, however, as I see this error on startup:

```
Caused by: com.google.inject.OutOfScopeException: Cannot access scoped [my.package.EventQueue]. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
```

Where my Service class looks like:
~~~
open class Service @Inject internal constructor(
    private val eventQueue: EventQueue
) {
~~~

and `EventQueue`

~~~
@RequestScoped
class EventQueue : Iterable<Event> {
    private val queuedEvents: Queue<Event> = LinkedList()

    fun queueEvent(event: Event) {
        queuedEvents.add(event)
    }

    override fun iterator(): Iterator<Event> {
        return queuedEvents.iterator()
    }

}
~~~

**Comment by mustafashabib** [comment]
Also noticing that my `service` classes are not being affected by my custom interceptor, rather, only those with `JdbiRepository` are getting hooked in. Unclear as to why. My Service classes are all marked as `Singleton` scope, if that matters.

Thank you again.

**Comment by mustafashabib** [comment]
I see a bit of what's going on, and documenting here for others who may face a similar situation.

* Kotlin classes and methods on them are final by default. You must explicitly make them `open` if you plan on intercepting them with Guice.

**Comment by xvik** [comment]
As I can see you answered all the questions so I will just comment on this:

> But not sure how to make it register before the JdbiModule - is there an Order annotation I can use?

The interceptors list report section is sorted to be the same on all systems. You should look below where it shows how interceptors applied to methods where interceptors order is preserved:

```
MyService    (c.s.p.b.service)
        └── toString()                                                        TransacationalEventInterceptor, TransactionalInterceptor
```

(correct order)

Generally, modules follow the registration order, so in most cases, it is enough to just register module earlier in the builder. In your case, order is correct because bundle processing will be delayed and so jdbi module will be registered after your module.

Tell me if I missed some questions requiring an answer or please close it if nothing else remains. I'll also put kotlin warning in the aop report docs (just in case).

**Comment by mustafashabib** [comment]
Yes, thanks!
