### ISSUE TITLE
guicey-bom `dropwizard.version` no longer respected via gradle + spring dependency management plugin

### ISSUE THREAD

**Issue by smorel-plenty** [xvik/dropwizard-guicey#114]
- Using gradle + the spring dependency management plugin (see snippet below). I haven't tried via a maven build but the spring dependency management plugin tries to be as faithful to the maven dependency resolution as possible.

The 5.0.1 guicey-bom included the dropwizard-bom so setting `dropwizard.version` would allow choosing a different dropwizard version. the 5.1.0 guicey-bom includes dropwizard-guicey. It seems that dropwizard-guicey's pom's hard coded dropwizard.version property is what's picked instead of the bom property.

I *think* it should be safe for both gucey-bom and dropwizard-guicey to import the dropwizard-bom? I know they haven't made dropwizard very easy to import cleanly.

```
    dependencyManagement {
        imports {
            // NOTE: Order of bom imports matters.
            // https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/html/#dependency-management-configuration-bom-import-multiple
            mavenBom("ru.vyarus.guicey:guicey-bom:5.1.0-2") {
                bomProperties([
                        "dropwizard.version": "2.0.11", // *** this doesn't work
                ])
            }
```

**Comment by xvik** [comment]
It should have never been working like that. I add these properties in bom just to let you reference used versions (for information only) and not to change anything. 

If you look 5.0.1 [guicey-bom](https://repo1.maven.org/maven2/ru/vyarus/guicey/guicey-bom/5.0.1-1/guicey-bom-5.0.1-1.pom) you can make sure that property is not used at all. The same for [main guicey bom](https://repo1.maven.org/maven2/ru/vyarus/dropwizard-guicey/5.0.1/dropwizard-guicey-5.0.1.pom) (imported by guicey-bom)

I was always suggesting to override dropwizard version by [direct bom inclusion](http://xvik.github.io/dropwizard-guicey/5.0.1/extras/bom/#setup):

```
dependencyManagement {
    imports {
        mavenBom "ru.vyarus.guicey:guicey-bom:5.0.1-1"    
        mavenBom 'io.dropwizard:dropwizard-dependencies:2.0.2'
    }
}
dependencies {
    implementation 'ru.vyarus:dropwizard-guicey'
}
```

The trick was working because of dropwizard bom itself: see [2.0.0 using property](https://repo1.maven.org/maven2/io/dropwizard/dropwizard-bom/2.0.0/dropwizard-bom-2.0.0.pom) and [2.11 without using property](https://repo1.maven.org/maven2/io/dropwizard/dropwizard-bom/2.0.11/dropwizard-bom-2.0.11.pom). Anyway, it was still an incorrect way because this trick was not updating dropwizard-dependencies bom and so you could (very likely) have incorrect transitive dependencies.

-----

In newer versions I [switched docs to native gradle bom support](http://xvik.github.io/dropwizard-guicey/5.1.0/extras/bom/#setup):

```
dependencies {
    implementation platform('ru.vyarus.guicey:guicey-bom:5.1.0-2')
    implementation platform('io.dropwizard:dropwizard-dependencies:2.0.10')

    implementation 'ru.vyarus:dropwizard-guicey'
}
```

I was using spring plugin for a long time and was always suggesting to use it instead of gradle support, but eventually, I give up because native gradle is much better:
* Elegant syntax
* It **does not apply bom to all configurations** by default (leading to hard to track dependency changes)
* Sometimes spring plugin is not working at all in multi-module setups (quite rare, but still).

Spring plugin is better when you declare (create) non-trivial bom (e.g. with exclusions). For bom usage native gradle is much better (ofc. there are edge cases, but I did not face them personally).
