### ISSUE TITLE
Using `RequestScoped` in scheduled jobs

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey#115]
Hello

I have a `@Singleton` class (`FooService`) that uses a `@RequestScoped` provider (`Provider<RequestScopedThing>`) to do some work. In a web context, this works as expected.

I want to inject that same `FooService` in my scheduled job but cannot, since the `RequestScoped` object is unavailable. How can I specify a different scope or manually create a `Provider` for this property in the context of my scheduled job?

Error that comes from guice is:

~~~
com.google.inject.OutOfScopeException: Cannot access scoped [my.package.RequestScopedThing]. 
Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply 
com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
~~~

Thanks

**Comment by xvik** [comment]
Hello! You can't use it this way because you need a real request in order to access the request scope.

> How can I specify a different scope or manually create a Provider for this property in the context of my scheduled job?

You can implement your own scope which will work as request scope with fallback to something else when request is not available, but it is definitely not a good way to go.

The best way is to re-design FooService or a scheduled job to not use request scoped beans
(If I'm not misunderstanding your question).

**Comment by mustafashabib** [comment]
We went with this approach for the record

~~~
final RequestScoper scope = ServletScopes.scopeRequest(Collections.emptyMap());
    try (final RequestScoper.CloseableScope ignored = scope.open()) {
      run(jobExecutionContext);
    }
~~~

**Comment by xvik** [comment]
Thank you for the workaround! I [added it into the docs](http://xvik.github.io/dropwizard-guicey/5.1.0/guide/guice/scopes/#request-scope-simulation) (just in case)
