### ISSUE TITLE
TestGuiceyAppExtension not registering

### ISSUE THREAD

**Issue by muliyul** [xvik/dropwizard-guicey#165]
I'm using a field extension but it does not appear to be registered:

```kotlin
@JvmField
@RegisterExtension
final val app = TestGuiceyAppExtension.forApp(...)

@Inject
lateinit var service: MyService // attempting to access in test results in NPE (`UninitializedPropertyAccessException`).
```

Is it possible to inject `app` as a class field?

**Comment by xvik** [comment]
The extension field [must be static](http://xvik.github.io/dropwizard-guicey/5.3.0/guide/test/junit5/#alternative-declaration) because currently guice context is started per test (before the first test and shutdown after last test in class).
Context per test method maybe would be supported in later versions (not 100% sure, but thinking about it).

`Application` is not bound [by default](http://xvik.github.io/dropwizard-guicey/5.3.0/guide/guice/bindings/), but you can inject the `Bootstrap` object and obtain application instance from it (`bootstrap.getApplication()`). 

Or you can bind the application yourself, for example, in a test-only module registered with [hook](http://xvik.github.io/dropwizard-guicey/5.3.0/guide/test/junit5/#application-test-modification).

**Comment by muliyul** [comment]
Actually I'm not looking for the application instance. I want each method to define it's own mocks (say mock a 3rd party client responses)

**Comment by xvik** [comment]
Yes, unfortunately, you can only declare test-class-wide mocks.
But, you could try to reset mocks state between tests manually (for example, mockito supports it). In this case, MocksModule would contain bare mock instances and each test would first declare the required behavior on it (using injected service instance) and reset could be done in afterTest lifecycle method.

If "mocks" are manual (no mockito or anything else), then you can add support for manual reset directly there (so custom impl would just need a method to reset "mocked" data, called by each test to reconfigure service). 

If none of this is possible then the best way now would be to use a single test per class to comfortably declare required mocks for each test (and have a fresh context each time).

[Junit4 guicey rule](http://xvik.github.io/dropwizard-guicey/5.3.0/guide/test/junit4/#testing-core-logic) supports restarting context for each test method and so it could be used instead (even with junit5 through the vintage engine to not completely downgrade). 

As I said before, the probability that context per test method support will be added later is high (if there would not be any blocking conflicts). But not too soon (I would need to do a small release to test the new release scheme, maybe it will be added there, but no promises)

**Comment by muliyul** [comment]
Some of these options came to mind but I was afraid of having to run the test serially. Do you see any issue with resetting mocks in regards to parallelism?

**Comment by xvik** [comment]
Yes, ofc such resets would make parallel tests impossible. By default, parallel tests are not enabled, so no problem. But even if you want to enable them, it is possible to [configure parallel execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution) only for different test classes (same thread for methods in class). In this case everything would be ok.

**Comment by xvik** [comment]
Since guicey 5.6.0 junit 5 extensions allow [starting application for each test method](http://xvik.github.io/dropwizard-guicey/latest/about/release-notes/#start-application-for-each-test-method)
