### ISSUE TITLE
Managed Object injection

### ISSUE THREAD

**Issue by sheldon-sminq** [xvik/dropwizard-guicey#19]
I am using a managed object for a Elastic search client, I need to inject this managed object into a class to get an instance of the client. Is this possible?

```
public class JestClientManaged implements Managed {
    private JestClient jestClient;

    @Override
    public void start() throws Exception {
        final Supplier<LocalDateTime> clock = () -> LocalDateTime.now(ZoneOffset.UTC);
        AWSCredentials credentials = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);
        AWSCredentialsProvider awsCredentialsProvider = new AWSStaticCredentialsProvider(credentials);
        final AWSSigner awsSigner = new AWSSigner(awsCredentialsProvider, region, "es", clock);
        final AWSSigningRequestInterceptor requestInterceptor = new AWSSigningRequestInterceptor(awsSigner);
        final JestClientFactory factory = new JestClientFactory() {
            @Override
            protected HttpClientBuilder configureHttpClient(HttpClientBuilder builder) {
                builder.addInterceptorLast(requestInterceptor);
                return builder;
            }
            @Override
            protected HttpAsyncClientBuilder configureHttpClient(HttpAsyncClientBuilder builder) {
                builder.addInterceptorLast(requestInterceptor);
                return builder;
            }
        };
        factory.setHttpClientConfig(
                new HttpClientConfig.Builder(ES_ENDPOINT)
                        .multiThreaded(true)
                        .build());
        jestClient = factory.getObject();
    }

    public JestClient getClient() {   //need to access this instance
        return jestClient;
    }

    @Override
    public void stop() throws Exception {
        jestClient.shutdownClient();
    }
}
```

**Comment by xvik** [comment]
Hi,

If `JestClientManaged` is registered by guicey (with auto scan or manually) then it's a guice bean and you can inject it anywhere you want. Just don't forget to annotate bean with `@Singleton` (as managed installer didn't force singletons).

Better option would be to make provider:
```java
public class JestClientManaged implements Managed, Provider<JestClient>{
```

And add manul guice binding (in guice module):

```java
bind(JestClient.class).toProvider(JestClientManaged.class);
```

And to be completely safe:

```java
public JestClient get() {   
        return Preconditions.checkNotNull(jestClient, "Client not initialized yet");
    }
```

As before, guicey will register JestClientManaged binding and register managed, but now you can do:

```java
@inject Provider<JestClient> clientProvider;
```

The reason why you will have to inject provider and not JestClient directly is delayed client creation (managed started after guice injector creation): many guice beans will require client instance on injector creation (because guice by default will start in production mode) and your provider would not be able to provide it yet.

One more option could be creating client in guice module and register client instance directly:

```java
bind(JestClient.class).toInstance(jestClient);
```

This way you can use direct client injection and make your managed use injected client instance (managed will only shutdown it).

**Comment by sheldon-sminq** [comment]
Thanks for the suggestions, we are currently creating client directly
inside module. But moving this into a managed object /provider looks
cleaner.
