### ISSUE TITLE
Dependency Convergence issue

### ISSUE THREAD

**Issue by BenRomberg** [xvik/dropwizard-guicey#20]
First of all, thanks for providing such a good Guice library for Dropwizard! We've just migrated from dropwizard-guice because of the unsolved issues it has with Dropwizard 1.0 and we were very happy how smooth the transition was.

We're using the very helpful `maven-enforcer-plugin` that allows you to require dependency versions to converge (see http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html for more details). It seems that dropwizard-guicey has a Dependency Convergence issue with its dependencies and it would be very helpful if it could resolve this by itself so we don't need to manage its dependencies in the future.

The issue raised is as follows:
```
Dependency convergence error for com.google.inject:guice:4.1.0 paths to dependency are:
  +-ru.vyarus:dropwizard-guicey:4.0.0
    +-com.google.inject.extensions:guice-servlet:4.1.0
      +-com.google.inject:guice:4.1.0
and
  +-ru.vyarus:dropwizard-guicey:4.0.0
    +-com.google.inject.extensions:guice-multibindings:4.1.0
      +-com.google.inject:guice:4.1.0
and
  +-ru.vyarus:dropwizard-guicey:4.0.0
    +-org.glassfish.hk2:guice-bridge:2.4.0-b34
      +-com.google.inject:guice:3.0
```

It seems that multiple libraries used by dropwizard-guicey are using different versions of Guice. Right now, we have to add the following `dependencyManagement` to our projects for the plugin to succeed:
```
      <!-- ru.vyarus:dropwizard-guicey -->
      <dependency>
        <groupId>com.google.inject</groupId>
        <artifactId>guice</artifactId>
        <version>4.1.0</version>
      </dependency>
```

It would be great if you could avoid this issue in future versions by adding an exclusion of Guice to the `org.glassfish.hk2:guice-bridge:2.4.0-b34` dependency, or use a more recent version of this dependency that also uses Guice 4.1.0. Also, I would recommend you to use a dependency convergence plugin for dropwizard-guicey as well (if it exists for Gradle) to prevent those issues from arising in the future. If you want, I'd also be willing to investigate this further if you'd accept a PR for this.

**Comment by xvik** [comment]
Hi,
Good point, thank you. I already got common to gradle conflict resolution strategy and forgot about maven: gradle takes upper version and maven takes the closest version (in dependency graph). 

The simplest solution would be to include direct guice reference and not rely on transitive inclusion by extensions. I will do it today.

Now regarding convergence plugin. Gradle has similar feature out of the box:

```groovy
configurations.all {
    resolutionStrategy.failOnVersionConflict()
}
```

But it doesn't work for guicey (guice conflict is not caught). Probably this is due to spring [dependency-management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) (used to import guice and dropwizard boms). I will dig into this if I have time, but I don't consider this as high priority (I understand benefits and agree that version control is a good thing in general, but not necessary for small projects like guicey).

**Comment by BenRomberg** [comment]
Thanks for the prompt response! This is absolutely a nice-to-have - we have those issues with some other libraries as well and always encourage the authors to fix them in the long term to make our life (and those of other users) easier in the future, but not anything we absolutely need to use dropwizard-guicey :-)
