### ISSUE TITLE
App startup fails with IllegalStateException: No generator was provided and there is no default generator registered

### ISSUE THREAD

**Issue by Kalyan-M** [xvik/dropwizard-guicey#208]
I have a project with dropwizard 2.0.25, using dropwizard-guicey. The app is not starting up with the following error:
```
WARN  [2022-01-05 01:31:33,278] [main] [] [logger]: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
WARN  [2022-01-05 01:31:33,278] [main] [] [Application_context]: unavailable
java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:285)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:245)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:90)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:62)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:38)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:55)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:73)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:69)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
.
.
.
at io.dropwizard.Application.run(Application.java:94)
```
```
ERROR [2022-01-05 01:31:33,328] [main] [] [ServerCommand]: Unable to start server, shutting down
javax.servlet.ServletException: jersey==io.dropwizard.jersey.setup.JerseyServletContainer@baa68670{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:null,STARTED}
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
```
These hk2 dependencies are present in classpath:
![image](https://user-images.githubusercontent.com/24321730/148123946-29bc71c3-d02d-42fc-99f5-040d58adcc00.png)

**Comment by xvik** [comment]
The default implementation is located in the `hk2-locator` jar, so it should work in your case. 

My guess is that you use OSGi or modules path - something making the required jar invisible at runtime.
Another possibility is an incorrect flat jar (shadow jar): it could avoid copying  `hk2-locator.jar/META-INF/services/org.glassfish.hk2.extension.ServiceLocatorGenerator`. Or, if package relocation used for ServiceLocatorGenerator, it would break lookup.  

The best way is to debug it, most likely it would bring some clues.

**Comment by Kalyan-M** [comment]
Thanks for the reply. I have limited knowledge of how shadow jars work. Can you please elaborate more on this? 
>  it could avoid copying hk2-locator.jar/META-INF/services/org.glassfish.hk2.extension.ServiceLocatorGenerator
I have a shadow jar as dependency and in intellij I can see it has `org > jvnet > hk2 ...` structure and glassfish relocated as `app.shade > org > glassfish > hk2 . . .`

> Or, if package relocation used for ServiceLocatorGenerator, it would break lookup.
As I said above, I have a dependency which has used package relocation. But why does it matter? If I have the original org.glassfish.hk2 dependencies in the classpath as the screenshot shows, won't those dependencies be used instead of whatever is present in shadow jar?

**Comment by xvik** [comment]
The problem with relocation is in breaking the service loader mechanism:
If your application  use relocated `app.shade.org.glassfish.hk2.extension.ServiceLocatorGenerator` then service lookup tries to find
`META-INF/services/app.shade.org.glassfish.hk2.extension.ServiceLocatorGenerator` which does not exist (existing file is `hk2-locator.jar/META-INF/services/org.glassfish.hk2.extension.ServiceLocatorGenerator`).

> If I have the original org.glassfish.hk2 dependencies in the classpath as the screenshot shows, won't those dependencies be used instead of whatever is present in shadow jar?

In case of package relocation, shadow jar not only moves class files to other packages but also has to change imports in all classes using these moved classes (otherwise classes would try to use classes from original packages and fail to load them) and so all affected files would use moved class. And if you'll have original jars in classpath it doesn't matter - code does not use it already. 

> I have a dependency which has used package relocation

Hard to suggest anything here - it's too specific. If possible try to avoid this dependency. Otherwise, you can create missed `/META-INF/services/app.shade.org.glassfish.hk2.extension.ServiceLocatorGenerator` (with implementation reference) and maybe it would even work, but hard to predict side effects (I assume part of the application could use normal hk and so you'll end up with multiple contexts)

**Comment by Kalyan-M** [comment]
In the dependency, I relocated `org.jvnet.hk2` to `app.shade.org.jvnet.hk2` and now it is working.
Thanks for the explanation.
What is weird is that the same dependency version was working before I upgraded dropwizard (which also included upgrading from jersey 1 to 2).
I faced similar issue with netty too. My app depends on app B, and B is a shadow jar. B has not relocated `org.jboss.netty`. But when I run my app, it tries to use the classes from shadow jar instead of netty jar. Is there a way to control this?
For now, I used a non shaded jar for the dependency.

**Comment by xvik** [comment]
> I faced similar issue with netty too. My app depends on app B, and B is a shadow jar. B has not relocated org.jboss.netty. But when I run my app, it tries to use the classes from shadow jar instead of netty jar. Is there a way to control this?

I don't understand this exact case, but there must be netty relocation because otherwise, it can't go wrong. The problem is the initialization chain: your application at some point use class from a shadowed jar with rewritten imports and this class triggers shadowed netty initialization (might be long or not obvious chain). 

There are maven/gradle plugins for automatic detection when classes from specific packages are used, but to configure it properly you need to know initialization chains to forbid root packages... and knowing it you'll unlikely to make a mistake. No way to prevent such cases in general.

The best way is to avoid shadowed jars at all costs (they always cause problems). 

> For now, I used a non shaded jar for the dependency.

I'm glad you could avoid it in your case.

**Comment by Kalyan-M** [comment]
> I don't understand this exact case, but there must be netty relocation because otherwise, it can't go wrong.

Actually, the dependency B shadowed netty but didn't relocate it. My app uses an old HTTP client that requires older version of netty, and my app seems to be picking the newer shadowed version of netty from B during runtime which doesn't have some method.
Atleast that's what I think is happening.

Anyway, closing this issue. Doesn't seem to be a guicey issue anyway. Again, thanks for your help.
