### ISSUE TITLE
Maven multi module project 

### ISSUE THREAD

**Issue by sheldon-sminq** [xvik/dropwizard-guicey#21]
How do we use the autoconfig option in a maven multi module project? I have module classes spanned across multiple maven modules.

**Comment by xvik** [comment]
It doesn't matter how many maven modules you have: at the end, it's a single classpath.

For example, if your project base package is `com.project` and modules packages are `com.project.module1`, `com.project.module2`, etc. then you can configure auto scan for `com.project` and all extensions will be resolved. Also, you can configure *multiple* packages to scan.

But I propose to think better about your modules if you can use [bundles](https://github.com/xvik/dropwizard-guicey#guicey-bundles) instead of part of classpath scan: [motivation](https://github.com/xvik/dropwizard-guicey#motivation).

If you separate modules "by layer" (e.g. model, dao, service) then it's harder to use bundles (because all parts are often changing). But if you split module "by feature" you can easily introduce bundles for features and install bundles manually or with [automatic lookup](https://github.com/xvik/dropwizard-guicey#service-loader-lookup). This way you could switch off/on features easily and, in case of generic modules, easily extract and re-use them in other projects.

**Comment by sheldon-sminq** [comment]
thanks for suggestions, managed to get bundles working.
