### ISSUE TITLE
Private Module with Path extension causes exception

### ISSUE THREAD

**Issue by pandaadb** [xvik/dropwizard-guicey#22]
Hi,

I am trying to get a private module to create a Resource class for me, then expose it, and have it installed via the ResourceInstaller. The reason is, that I have very specific configuration classes that should not be exposed to any other modules in the system. So I try and configure my resource within the  PrivateModule and expose it from there. 

Here is a minimal example to replicate this issue: 

```
public class GuiceyApplication extends io.dropwizard.Application<Configuration>{

	@Override
	public void initialize(Bootstrap<Configuration> bootstrap) {
		
		AbstractModule m = new AbstractModule() {
			protected void configure() {
				
				install(new PrivateModule() {
					@Override
					protected void configure() {
						Map<String,String> props = new HashMap<>();
						props.put("private.specific.property", "pandaadb");
						Names.bindProperties(binder(), props);
						bind(Config.class).in(Singleton.class);
						
						// this is the resource we want to bind, but instantiate privetly 
						bind(Resource.class).in(Singleton.class);
						
						// expose it for others to use/be injected
						expose(Resource.class);
					}
				});
			};
		};
		
		
		bootstrap.addBundle(GuiceBundle.<Configuration>builder()
				.modules(m) // bind the module for resource CREATION
				.extensions(Resource.class) // add extension for jersey binding
				.build()
	    );
	}
	
	@Override
	public void run(Configuration configuration, Environment environment) throws Exception {
		
	}
	
	public static void main(String[] args) throws Exception {
		new GuiceyApplication().run("server", "/home/artur/dev/repo/sandbox/src/main/resources/config/test2.yaml");
	}
	
	// want to hid this
	public static class Config {
		
		private String test;

		@Inject
		public Config(@Named("private.specific.property")String test) {
			this.test = test;
		}
		
	}
	
	@Path("test")
	public static class Resource {
		
		private Config c;

		@Inject
		public Resource(Config c) {
			this.c = c;
		}
		
		@GET
		public String getConfigValue() {
			return c.test;
		}
	}
	
}
```

As you can see, I am creating the Config class and the Resource in the PrivateModule. This works fine (i think). Then i expose the Resource as an extension. My hope was that Guicey would detect that the resource has been created and simply use the resource. However, running above code will yield this exception: 

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unable to create binding for guiceyTest.GuiceyApplication$Config. It was already configured on one or more child injectors or private modules
    bound at guiceyTest.GuiceyApplication$1$1.configure(GuiceyApplication.java:36) (via modules: guiceyTest.GuiceyApplication$1 -> guiceyTest.GuiceyApplication$1$1)
  If it was in a PrivateModule, did you forget to expose the binding?
  while locating guiceyTest.GuiceyApplication$Config
    for the 1st parameter of guiceyTest.GuiceyApplication$Resource.<init>(GuiceyApplication.java:83)
  at ru.vyarus.dropwizard.guice.module.installer.feature.jersey.ResourceInstaller.install(ResourceInstaller.java:46) (via modules: ru.vyarus.dropwizard.guice.module.GuiceSupportModule -> ru.vyarus.dropwizard.guice.module.installer.InstallerModule)

2) A binding to guiceyTest.GuiceyApplication$Resource was already configured at guiceyTest.GuiceyApplication$1$1.configure(GuiceyApplication.java:42) (via modules: guiceyTest.GuiceyApplication$1 -> guiceyTest.GuiceyApplication$1$1).
  at ru.vyarus.dropwizard.guice.module.installer.feature.jersey.ResourceInstaller.install(ResourceInstaller.java:46) (via modules: ru.vyarus.dropwizard.guice.module.GuiceSupportModule -> ru.vyarus.dropwizard.guice.module.installer.InstallerModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at ru.vyarus.dropwizard.guice.injector.DefaultInjectorFactory.createInjector(DefaultInjectorFactory.java:20)
	at ru.vyarus.dropwizard.guice.GuiceBundle.createInjector(GuiceBundle.java:191)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:138)
	at ru.vyarus.dropwizard.guice.GuiceBundle.run(GuiceBundle.java:93)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at guiceyTest.GuiceyApplication.main(GuiceyApplication.java:62)
```

I am not sure how to get around this issue other than probably implement EnvironmentAwareModule and install the resource manually to the right path. 

Is this a supported feature? I am not sure how to go about it. 

Edit: This works perfectly fine if everything done is in the parent mopdule (not the private one) 

Thanks,

Artur

**Comment by xvik** [comment]
Hi,

Try annotating your resource with `@LazyBinding` - it should solve your problem.

By default guicey [binds all resolved extensions](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/InstallerModule.java#L192). This avoid guice JIT resolution (because at the end all components are declared) to let you use restricted  guice options. At this point, it is impossible to know if component already bound because guice context is in creation phase (and not all modules are registered).  If some extension class is annotated with `@LazyBinding` it's simply not bound.

Some installers may override binding by implementing [BindingInstaller](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/install/binding/BindingInstaller.java) and do bindings manually.  In such case, installer may or may not support `@LazyBinding` marker (normally installer should fail if lazy marker is not supported, but used) and, if lazy supported, implement its meaning,

[ResourceInstaller](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/jersey/ResourceInstaller.java#L43) did custom bindings, but honor lazy marker. So annotated method will not be bound to guice context, but registered in dropwizard (so overall everything will work). 

I know LazyBinding name is misleading for this case, but it was added exactly for "lazy initialization" cases to delay component creation (in context of HK2 integrations). 

p.s. I saw your responses about guicey on stackoverflow and finally I have a chance to say thank you!

**Comment by pandaadb** [comment]
Hi 

heh you are very welcome :) This seems to also be a guice issue as i can replicate it without Guicey as well. 

The LazyBinding however works perfectly.

I am the one to thank you - just promoting a great integration I've been using happily for 1+ years now :) I was wondering how to contribute, but I seriously have not yet found functionality I am missing. If you need a helping hand though, you can let me know and I can try and help out :) 

Other than that - thanks for your help. I'm closing this issue too :)
