### ISSUE TITLE
The method `configure()` of module is called twice

### ISSUE THREAD

**Issue by race604** [xvik/dropwizard-guicey#223]
As title, the method `configure()` is called twice for each module when `.printGuiceBindings()`, here is sample code reproduce:

```kotlin
class TestModule: DropwizardAwareModule<Configuration>() {
    override fun configure() {
        println("TestModule configure() is called")
        // other config logic
    }
}

class SampleApplication : Application<Configuration>() {

    override fun initialize(bootstrap: Bootstrap<Configuration>) {
        bootstrap.addBundle(
            GuiceBundle.builder()
                .enableAutoConfig(javaClass.getPackage().name)
                .modules(TestModule())
                .printGuiceBindings()
                .build()
        )
    }

    override fun run(configuration: Configuration?, environment: Environment?) {
    }
}

fun main(args: Array<String>) {
    SampleApplication().run(*args)
}

```

This is the console output:

```
INFO  [2022-04-27 13:41:00,390] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
TestModule configure() is called
...
INFO  [2022-04-27 13:41:01,436] org.eclipse.jetty.server.Server: Started @2683ms
TestModule configure() is called
```

I suppose this is unexpected that the `configure()` be called twice.

**Comment by xvik** [comment]
Thank you for the report! 
It's an expected behaviour: guice SPI, used for bindings analysis, has to execute all modules in order to collect bindings.

But there is a way to differentiate calls: report-related cofniguration is executed with stage TOOL, so you can avoid sensitive logic duplication in guice module with a simple check:

```java
if (binder.currentStage() != Stage.TOOL) {
    // do only on normal run
}
```

Guicey itself use this, for example in [jersey providers installer](https://github.com/xvik/dropwizard-guicey/blob/cd27331656ddff82d6a6a7738010c173da1df5f8/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/jersey/provider/JerseyProviderInstaller.java#L117) to avoid duplicates in console report.

I was sure it is stated in docs, but it is not :( 
I'll update docs

**Comment by race604** [comment]
Thanks for the comprehensive explanation, appreciate it. The `stage` check will help in my case.
