### ISSUE TITLE
Guicey causes WARN logs during service start even when everything is OK

### ISSUE THREAD

**Issue by rhatlapa** [xvik/dropwizard-guicey#276]
I've noticed this change https://github.com/xvik/dropwizard-guicey/commit/c2fc765d862490375ff97fd6e533dedc36c1b43a, which changes the behaviour and prints these logs as WARNs. From the commit nessage I don't understand the actual reasoning, could you please provide more info?

Is it due https://github.com/dropwizard/dropwizard/blob/81d6b6ef8b92f8a67ead232a15ad799602a2e9b1/dropwizard-logging/src/main/java/io/dropwizard/logging/BootstrapLogging.java#L36? If so it doesn't make sense, the actual user should rather update the logging level if the user wants to see those messages. Forcing such message on WARN logs causes issues and it shall result in hiding these messages rather than having WARN logs printed when everything works fully correctly.

**Comment by xvik** [comment]
Yes, It was done because of the default WARN level so reports could be seen in any case (for example, in tests).
These reports supposed to be used for one-shot debug (enable - verify - disable). I doubt these reports are used in production.

> Forcing such message on WARN logs causes issues and it shall result in hiding these messages rather than having WARN logs printed when everything works fully correctly.

What issues? Could you please descibe your situation (is some report is always enabled in your app?)

There is a possible alternative: to write such reports directly into output stream (system.out, like lifecycle report already did) instead of using logger. This way reports would be always visible and without WARN marker. Maybe, it would be a better way.
Open for discussion.

**Comment by rhatlapa** [comment]
The log message `Diagnostic report` we are getting in production code after upgrade to the newest dropwizard revion and it is printed after every service start. I am not aware of any customizations which would request these reports to be done during the start => to me it seems as something printed by default.

**Comment by rhatlapa** [comment]
Is there some option to disable this report to be printed?

Regarding the alternative, I would stay with logging as it gives more options to parse such logs or change its formatting (e.g. to make use of a logging in a JSON format)

**Comment by rhatlapa** [comment]
I've managed to find the place where we are calling `printDiagnosticInfo` => the report generation is in our code.

**Comment by xvik** [comment]
Diagnostic log could be [enabled manually](http://xvik.github.io/dropwizard-guicey/latest/guide/diagnostic/configuration-report/) (as in your case) with `printDiagnosticInfo()` or [with system property](http://xvik.github.io/dropwizard-guicey/latest/guide/hooks/#diagnostic) `-Dguicey.hooks=diagnistic`

So you suggest to revert to INFO logs instead of system output.

I just [created a pool](https://github.com/xvik/dropwizard-guicey/discussions/277). Anyone reading this please participate or write your opinion here. I'm really not sure what would be the best way. I hope to hear more real use-cases

**Comment by rhatlapa** [comment]
Yes, I still suggest reverting to INFO as such log message doesn't indicate anything being wrong. For our use case, I would say we mostly need this information during development process and changes in modules => we are removing it from the production code.

Thank you for all the feedback and also for the info about the system property. That solves the issue for our use case.
