### ISSUE TITLE
Dependency Management Issues In 5.8.0

### ISSUE THREAD

**Issue by JKomoroski** [xvik/dropwizard-guicey#302]
I use the [Dependency Versions Check](https://github.com/basepom/dependency-versions-check-maven-plugin) maven plugin to verify my classpath dependencies are current. After moving to guicey version `5.8.0` from `5.7.1` I found that Guava was not being managed correctly anymore. I went back to `5.7.1` and the issue went away. 

Error:
```
[INFO] --- dependency-versions-check-maven-plugin:3.2.0:check (basepom.default) @ mod ---
[INFO] Checking direct dependencies for 'test' scope, reporting only conflicts
[ERROR] com.google.guava:guava: 30.1-jre (direct) - scope: compile - strategy: default
       30.1-jre expected by *my.app.package:mod*, com.google.inject:guice
       31.1-jre expected by ru.vyarus:dropwizard-guicey
```

A dependency tree showed that guice was first encountered in guicey and the upstream dropwizard bom was not taking priority. I'm not very familiar with Gradle but I found the following change to the guicey `build.gradle` seems to fix the issue for me:

```
dependencies {
    api platform("io.dropwizard:dropwizard-dependencies:$dropwizard")
    api platform("com.google.inject:guice-bom:$guice")
    ...
    ...
```

Currently it looks like:
```
dependencies {
    api platform("com.google.inject:guice-bom:$guice")
    api platform("io.dropwizard:dropwizard-dependencies:$dropwizard")
    ...
    ...
```

Is this the correct way to prioritize dependency management in gradle?

**Comment by xvik** [comment]
Oh, thank you! I'll release fixed versions for all branches.

The problem is not in gradle, but maven dependency resolution: maven always selects the nearest in depth and the first in resolution. Guava is on the same depth for both guice and dropwizard BOMs and that's why order in the generated pom matter.

Also, in guicey 5.7, there was a direct 1st level reference to correct guava version. In 5.8 I dropped spring dependency-management-plugin (maven inside gradle) in favour of native gradle platforms so I couldn't access BOM properties anymore and can't put always correct 1st level guava (anyway, it is not actually needed).

This problem appears only with BOM because correct exclusions applied to guicey transitive dependencies and so old guava did not appear with direct dropwizard-guicey usage (in 5.7 this exclusions were applied on BOM level).

**Comment by xvik** [comment]
By the way, the quick workaround is to manually specify correct guava version:

```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ru.vyarus.guicey</groupId>
                <artifactId>guicey-bom</artifactId>
                <version>5.8.1-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                <version>31.1-jre</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by JKomoroski** [comment]
Thanks. I understand the maven side. I think I understand how the bom is generated now as well. Thanks for the little quality of life fix.
