### ISSUE TITLE
java.lang.AbstractMethodError when using both JDBI and Governator

### ISSUE THREAD

**Issue by jmdesprez** [xvik/dropwizard-guicey#31]
Hello,

I try to use both [JDBI](http://xvik.github.io/dropwizard-guicey/4.0.1/extras/jdbi/) and [Governator](http://xvik.github.io/dropwizard-guicey/4.0.1/examples/governator/) on my project.
But I always end with this error: `java.lang.AbstractMethodError: MyRepository$GuiceDynamicClass.simpleTest()Ljava/lang/Integer;`

If I remove the Governator injector, the JDBI part works well

Regarding the Governator, I've followed the documentation (`GovernatorInjectorFactory` and the `GovernatorLifecycle` are copy past)
For the JDBI part, I've also followed the documentation

Is it possible to use JDBI with Governator?

Thanks

---

Here is some details on my code (if needed)
My repository:
```
@JdbiRepository
@InTransaction
public interface MyRepository {
    @SqlQuery("select 1")
    Integer simpleTest();
}
```
The resource:
```
@Path("/test")
@Api(value = "/test", description = "Test resource")
public class TestResource {
    private final MyRepository repository;
    @Inject
    public TestResource(final MyRepository repository) {
        this.repository = repository;
    }

    @GET
    @ApiOperation(value = "Simple test")
    @InTransaction
    public Response test() {
        final Integer integer = repository.simpleTest();
        return Response.ok(integer).build();
    }
}
```
The JDBI bundle is created like this:
```
JdbiBundle.<DWConfiguration>forDatabase((conf, env) -> conf.getDatabase())
```

**Comment by xvik** [comment]
Hi,
Just out of curiosity, can you please tell me what are you using from governator? I'm really curious.

Personally, I never used it. As I remember, governator use child injector (or starting 2 independent injectors). Anyway, jdbi integration is based on guice AOP: when annotated repository is called, the call is intercepted by aop handler which redirects call to real jdbi object.

According to the error above, aop handler is not used in your case. This could happen, for example, if aop handler was registered in child injector and repository bean is created in parent one (or other cases like this when handler and injector stay on different levels).

Can you provide some small test project (I assume you already have one) to reproduce the problem? With it, I will be able to tell you anything faster). In any case, I will look.

**Comment by jmdesprez** [comment]
Hello,

I use `@LazySingleton` from Governator but I think that `@Singleton` + injecting `Provider<MyClass>` instead of `MyClass` will achieve exactly the same goal? (maybe I'm wrong)

If so, I will simply stop using Governator ;)

**Comment by xvik** [comment]
Provider<Class> is almost always a good solution :) And yes, with @Singleton annotation on bean you can get "lazy singleton" behavior. But, such bean must not be registered manually in guice module (because guice will instantiate all known services at startup).

Normally you shouldn't need "lazy singleton", except some cases with 3rd parties integration (for example, I have such cases because of hk2, which starts after guice; another example is jdbi which has to access dbi instance only when its ready). In some cases, it makes sense to implement Provider directly to lazily initialize resource (on the first get() call). Guice (conceptually) likes the simplest solutions, so think of it and maybe you will realize that you don't need laziness at all.

All extensions, recognized by guicey are bound directly with the injector and so instantiated in the time of injector creation, but there is [a workaround for lazy init](http://xvik.github.io/dropwizard-guicey/4.0.1/guide/installers/#how-it-works) (its usage depends on the situation and, honestly, [almost never](http://xvik.github.io/dropwizard-guicey/4.0.1/installers/jersey-ext/#valuefactoryprovider) required).

**Comment by jmdesprez** [comment]
Ok so I will not use Governator and I can close :)

Thanks a lot for the very detailled explanation, it was really helpful
