### ISSUE TITLE
@Context on ContainerResponseFilter does not work

### ISSUE THREAD

**Issue by danyflorez** [xvik/dropwizard-guicey#35]
Hi, 

I have been developing a project with dropwizard-guicey, great help btw, Rignt now I'm setting up a security project and they have something like this:

@Provider
public class CorsFilter implements ContainerResponseFilter{

	@Context
	private HttpServletRequest httpServletRequest;

}

I know that that's not the correct way to inject the context but I need to figure out a way to make this work out, do you know how I could do that?

Thank you!

**Comment by pandaadb** [comment]
Hi,

this does seem to be the right thing. Are you using the extensions-system to actually register your provider with the jersey eco-system?

**Comment by danyflorez** [comment]
Hi, 

I'm using the enableAutoConfig to scan every class anotated with javax.ws.rs.ext.Provider like this

        bootstrap.addBundle(GuiceBundle.builder()
                .enableAutoConfig(getClass().getPackage().getName(),"co.com.company.security.service")
                .modules(new AfiliacionesModule(hibernate))
                .useWebInstallers()
                .build());

The provider gets called but the problem comes when they call httpServletRequest.getAttributeNames(), they get a Null pointer excepcion because HttpServletRequest  isn't getting injected,

I read in the documentation something like this "@Context annotation usage is a common point of confusion. You can't use it for class fields" but then how I inject it inside the filter 

@Provider
public class CorsFilter implements ContainerResponseFilter{

    @Context
    private HttpServletRequest httpServletRequest;

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext)
        throws IOException {
        this.httpServletRequest.getAttributeNames();
}

**Comment by pandaadb** [comment]
This is a bit of a later version of guicey than I have. But, I think the issue here is that at the time guice instantiates the provider, it can't find a request (makes sense). 

I vaguely remember that if you want a request scoped bean to be injected, you need to use a provider instead of the actual bean you need. So, in your case, that might mean :

@Inject Provider<HttpServletRequest> reqProvider; 

Sadly i can't try that now but I am pretty sure that is how I did that in the past. By using the provider, guice internally, when requestiong the servlet context, resolved the scope and returns the correct request.

**Comment by xvik** [comment]
@pandaadb is right: you can use Provider to access supported [request scoped objects](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/bindings/#jersey-specific-bindings).

Here is the exact link on [@Context confusion doc chapter](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/resource/#context-usage) in case someone else will read this.

Guicey register jersey extensions as instances (singletons) created by guice and that's why @Context on field can't work (guice does not support such injection).

And there is an other way...

@Context field injection could work only when hk2 manage bean. You can delegate bean management to hk by using @Hk2Managed ([example](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/bindings/#jersey-specific-bindings)) and this way @Context on field will work. 
If you'll go that way you may need to [enable guice bridge](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/configuration/#hk-bridge) to be able to inject other guice beans into hk managed beans.

I never recommend delegation to hk: I think Providers are good enough and it's always better to live only in guice world. But you have a choise.

**Comment by xvik** [comment]
Please reopen if it doesn't answer your question completely.
