### ISSUE TITLE
Support dropwziard 3.0.6

### ISSUE THREAD

**Issue by px100** [xvik/dropwizard-guicey#377]
https://github.com/dropwizard/dropwizard/releases/tag/v3.0.6

**Comment by xvik** [comment]
All guicey branches are already updated to the released dropwizard versions, but I usually wait for a week or two in case of urgent dropwizard bugfix releases. Will release all versions this weekend.

Anyway, it is always a good idea to ping me if you need release earlier (because I can delay release more if noone ask for it).

**Comment by xvik** [comment]
[6.2.2](https://github.com/xvik/dropwizard-guicey/releases/tag/6.2.2) released
