### ISSUE TITLE
Injecting class members?

### ISSUE THREAD

**Issue by mosheeshel** [xvik/dropwizard-guicey#4]
I have a Provider class, wired like so:
environment.jersey().register(NotFoundExceptionMapper.class);

I want to habe the member injected (this worked with Dropwizard 0.6 and 0.7 with [dropwizard-guice](https://github.com/HubSpot/dropwizard-guice/issues) project ), everything seems to be working except for this, what am I doing wrong?

Class code:
@Provider
@RequestScoped
public class NotFoundExceptionMapper implements ExceptionMapper<NotFoundException> {
    private final static Logger logger = LoggerFactory.getLogger(NotFoundExceptionMapper.class);

    @Inject
    private ShortRequestsHandler shortRequestsHandler;
    @Context
    private HttpServletRequest request;

    public NotFoundExceptionMapper() {
    }

**Comment by mosheeshel** [comment]
Resolved with Constructor injection, but would still like to know if there is a solution

**Comment by xvik** [comment]
I suppose you don't use guicey auto congiguration (classpath scan), because in this case you would not need to register mapper manually.

Most likely situation is: when you directly register class in jersey you let HK2 to manage instance creation.
If @Inject annotation is guice inject then HK ignore this field (it only knows javax.inject annotations).
HK guice bridge is registered, but it will work only for injection points and not able to resolve type directly (so if you have this exception mapper in guice context, hk will create it's own in any case).

I'm not a big fan of request scoped beans, so I would make this bean singleton and register request scoped objects as providers (and let guice manage bean):
@Inject // assume this bean is request scoped too
private Provider<ShortRequestsHandler> shortRequestsHandlerProvider;
@Inject // request, response and some jersey specific objects are available in guice context
private Provider<HttpServletRequest> requestProvider;

Please tell me what is your desired behavior and I would be able to tell you more details (maybe i should better describe how installers work). 
Can you tell me why you don't use classpath scan with installers (just curious)?
