### ISSUE TITLE
How does injection work in environment command?

### ISSUE THREAD

**Issue by x1a0** [xvik/dropwizard-guicey#46]
I have a command class extends `EnvironmentCommand`. In its constructor I have a parameter whose type has a provider in my module. However Guice still said:
```
Failed to instantiate command
```

All injection works fine in application.

Thanks!

**Comment by xvik** [comment]
Hi!

Your command must have a constructor with only one parameter: application ([as described in docs](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/commands/#environment-commands)).

Injections inside command are possible only as field injections because commands must be registered in dropwizard initialization phase (in the bootstrap object) when guice context is not yet ready. After guice start `injeector.injectMemebers(cmd)` is called for registered commands.
