### ISSUE TITLE
Injecting nested map fields

### ISSUE THREAD

**Issue by acchaulk** [xvik/dropwizard-guicey#57]
If I have a config with a `Map<String, String>`, I cannot inject nested properties. For example

```java
public class TestConfig extends Configuration {

  private Map<String, String> testMap = new HashMap<String, String>() {{
    put("testKey", "testValue");
  }};

  public Map<String, String> getTestMap() {
    return testMap;
  }

  public void setTestMap(Map<String, String> testMap) {
    this.testMap = testMap;
  }
}

@Provides
@Named("someKey")
public String getSomeValue(@Config("testMap.someKey") String value) {
  return value + "yay!";
}
```

I am able to inject the entire map itself, but when I try to inject nested fields I receive the following error:
`No implementation for java.lang.String annotated with @ru.vyarus.dropwizard.guice.module.yaml.bind.Config(value=testMap.someKey) was bound.
  while locating java.lang.String annotated with @ru.vyarus.dropwizard.guice.module.yaml.bind.Config(value=testMap.someKey)`

**Comment by xvik** [comment]
That is correct behavior: configuration introspection mechanism looks only configuration object (and sub-objects) properties but never dig inside maps (or any other common objects). This mechanism mainly solve the problem of configuration composition when each application part must be aware of global configuration object and not only it's relevant part (for example, some AuthService could require only AuthConfig and not the entire AppConfig).

With maps, you will almost certainly have "ghost" bindings. Imagine, you add some optional property to some map in configuration ("testMap.someKey"). Next, you rely on the direct binding on this property and someday someone will remove this optional map property (because it's optional!). The application will fail to start after that because of no required binding (as in your exception).

If you need such low-level bindings you can always do it yourself: there is a way to [access introspected configuration inside guice module](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/module-autowiring/#configuration-access). Something like this:

```java
public class MapBindingsModule extends DropwizardAwareModule<Configuration> {
    @Override
    protected void configure() {
        Map<String, String> conf = configuration("testMap");
        for(Map.Entry<String, String> entry : conf.entrySet()){
              LinkedBindingBuilder binding = bind(Key.get(String.class, new ConfigImpl("testMap."+entry.getKey());
                   if (value == null) {
                          building.toProvider(Providers.of(null));
                   } else {
                          binding.toInstance(value);
                   }
        }
    }
}
```

Register this module and you will be able to bind map values directly (`@Inject @Config("testMap.someKey") String value`)
