### ISSUE TITLE
Ordering of scanned classes

### ISSUE THREAD

**Issue by ritwikmitra** [xvik/dropwizard-guicey#58]
Question - Is there any way to define an order for the list of classes returned by the scanner?

Context:
I was trying to write a custom FeatureInstaller to register method interceptors. All interceptors implement a common interface which also allows them to specify which classes / methods to intercept.

Guice invokes interceptors based on the order in which they were registered. With the classpath scanner, there seems no way of defining the order, in which the classes are added to the scanned list.

If we could sort certain classes (based on something like a @ScanOrder annotation, before adding it to the scanned classes list, with a default value for all classes not specifying the order), we can ensure the classes returned by the scanner can follow some order.

**Comment by xvik** [comment]
Ordering of extensions [is supported](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/ordering/). Your installer just needs to implement [Ordered](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/installers/#ordering) interface to enable extensions order.

There is no difference if extension class is registered directly or found by classpath scan. But, as you asking, I assume that you're trying to perform extension installation just in time of detection:

```java
public class CustomInstaller implements FeatureInstaller<CustomFeature> {
    @Override
    public boolean matches(final Class<?> type) {
        return FeatureUtils.is(type, CustomFeature.class);
    }    
}
```

`matches` method must be used only to recognize extension. Installer must implement `TypeInstaller`, `IntsaceInstaller`, etc. in order to perform extensions installation.

For example, if you need extension instance to perform installation you should do:

```java
public class CustomInstaller implements FeatureInstaller<CustomFeature>, 
                                                  InstanceInstaller<CustomFeature>,
                                                  // enable ordering support (extensions called in order for installation)
                                                  Ordered {
    @Override
    public boolean matches(final Class<?> type) {
        // extension detection only
        return FeatureUtils.is(type, CustomFeature.class);
    }    

    public void install(Environment environment, CustomFeature instance) {
         // perform insatnce registration
        // note that extensions will be called according to @Order annotations (sorted)
    }
}
```
