### ISSUE TITLE
org.glassfish.hk2.api.UnsatisfiedDependencyException in ClientResponseFilter with Guice-managed dependency

### ISSUE THREAD

**Issue by maksymgendin** [xvik/dropwizard-guicey#62]
Hi!

I don't know what I'm doing wrong or if this is supposed to work at all...

A have a custom `javax.ws.rs.client.ClientResponseFilter` implementation which I add as a provider to my Jersey client. That custom filter has a dependency to a util class which is managed by Guice. I've enabled the HK2 guice-bridge but HK2 still cannot resolve this dependency for some reasons...

Here is my example project with failing test: https://github.com/maksymgendin/guice-hk2-failure

I would very appreciate your help.
Thanks in advance!

**Comment by xvik** [comment]
Hi!

Guicey does not do "low level" integrations, all it does is: obtain extension from guice context and properly register in dropwizard environment. It's essentially pure dropwizard way, but without manually instantiating object and manual registration.

So when you tell it to use extension:

```java
GuiceBundle.builder()
                           .extensions(
                                   TestResource.class
                           )
```

guicey will detect that `TestResource` is a resource ([because of path annotation](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/jersey/ResourceInstaller.java#L43)) and [register it in environment](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/jersey/ResourceInstaller.java#L75) (it will also "bridge" correct instance into hk2 context, but its internal detail)

`TestFilter` will not be installed, because [jersey installer](http://xvik.github.io/dropwizard-guicey/4.2.2/installers/jersey-ext/) does not support client filters (it's just too ambiguous). 

So to get your filter working you need to register it's instance manually:

```java
final Client client = new JerseyClientBuilder(RULE.getEnvironment())              
          .withProvider(InjectorLookup.getInjector(RULE.getApplication())
              .get().getInstance(TestFilter.class))
          .build("test-client");
```

Here you manually obtain filter instance from injector and register it.

If required it could be automated: you can write [your own installer](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/installers/#writing-custom-installer) (by analogy with [jersey providers installer](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/jersey/provider/JerseyProviderInstaller.java). I doubt you will do it, but you can.

All of the above does not require hk2-bridge at all.

Now why it doesn't work with activated bridge (in your case): simply because there is no binding in guice context (you never bind TestUtil, and you can't rely on guice JIT in case of hk2-bridge.

You can either register guice module, which will manually bind utils: `bind(TestUtil.class)`
or use guicey extension:

```java
@EagerSingleton
public class TestUtil {

GuiceBundle.builder()
                           .extensions(
                                   TestResource.class,
                                   TestUtil.class
                           )
```

Guicey will automatically bind TestUtil and hk-bridge will be able to find and inject this binding.

But I don't suggest to use hk-bridge.. it always complicates things (it's almost never really required). 
Moreover, I plan to get rid of it completely in the next version (but not in 5.0).

**Comment by maksymgendin** [comment]
@xvik Thanks for extensive explanation.
I'm aware about the first part. My problem is that in my real-life scenario I don't have access to the application class so I can't easily get the injector...that's why I'm trying to go with the bridge.

See my last commit https://github.com/maksymgendin/guice-hk2-failure/commit/094a729afab8713f2f1eee2bd09227659ef162a0. I've added an untargeted binding for `TestUtil` but it still doesn't work...

**Comment by maksymgendin** [comment]
@xvik Annotating `TestUtil` with `@EagerSingleton` and registering it as an extension also doesn't work...same `UnsatisfiedDependencyException`

**Comment by xvik** [comment]
You're right, `JerseyClientBuilder` always builds independent client.

The only way is to use jersey's client builder to share resource config:

```java
final Client client = ClientBuilder.newBuilder()
                .withConfig(RULE.getEnvironment().jersey().getResourceConfig())
                .register(TestFilter.class)
                .build();
```

But not sure if this is possible in your case (and that's there is no side effects), but it's the only way I see.

>  My problem is that in my real-life scenario I don't have access to the application class so I can't easily get the injector...that's why I'm trying to go with the bridge.

Possibly, but there is almost always a way for some workaround. If you want you can tell more about your case (I really don't like HK and try to avoid it at all costs).

**Comment by maksymgendin** [comment]
@xvik I'm also not sure that sharing resource config will not have any unexpceted effects 😄
My case is basically quite simple:
I've an extended version of `io.dropwizard.client.JerseyClientBuilder` which is constructed with `new` operator (without DI) and I have there access only to the `io.dropwizard.setup.Environment`. So I somehow have to get the injector from `io.dropwizard.setup.Environment`. Right now I figured out only a hacky solution by auto-registering a `io.dropwizard.lifecycle.Managed` object where I inject myself the injector:

```java
class InjectorManaged implements Managed {

    private final Injector injector;

    @Inject
    InjectorManaged(final Injector injector) {
        this.injector = injector;
    }

    private Injector getInjector() {
        return injector;
    }

    @Override
    public void start() {
        // nothing to do
    }

    @Override
    public void stop() {
        // nothing to do
    }
}
```

and then I've added a super-ugly static helper method to get the injector from `io.dropwizard.setup.Environment`:

```java
public static Injector getInjector(final Environment environment) {
    return environment.lifecycle()
                      .getManagedObjects()
                      .stream()
                      .filter(o -> JettyManaged.class.isAssignableFrom(o.getClass()))
                      .map(JettyManaged.class::cast)
                      .map(JettyManaged::getManaged)
                      .filter(o -> InjectorManaged.class.isAssignableFrom(o.getClass()))
                      .map(InjectorManaged.class::cast)
                      .map(InjectorManaged::getInjector)
                      .collect(MoreCollectors.onlyElement());
}
```

Do you maybe know a better way to do that?

**Comment by xvik** [comment]
Yes, there is a better way using jersey properties.. it seems to not validate keys:

Register property in application (`InjectorProvider` is a guicey class)

```java
 @Override
    public void run(final Configuration configuration,
                    final Environment environment) {
        environment.jersey().property("injector", new InjectorProvider(this));
    }
```

Access

```java
Injector injector = RULE.getEnvironment().jersey().<InjectorProvider>getProperty("injector").get() 
```

**Comment by maksymgendin** [comment]
@xvik Thanks for your help! Works like a charm.

**Comment by xvik** [comment]
Thank you too! I'll use this in the new version to support injector lookup by environment `InjectorLookup.getInjector(Environment)`.
