### ISSUE TITLE
QUERY: Change of behaviour with Governator

### ISSUE THREAD

**Issue by nheitz** [xvik/dropwizard-guicey#71]
I cannot quite determine if this is a guicey, dropwizard 2, or governator issue, so I thought I'd raise this first here.

In version 1.3.17 of dropwizard and version 4.2.2 of guicey, I was abole to use governator to specify multiple guice modules, even if they had duplicate bindings.  This was achieved by using governator's  *OverrideAllDuplicateBindings* module transformer, which effectively folds all the module using Guice's override mechanism.

Thus, the following guicey setup worked:

```
    this.guiceBundle = GuiceBundle.builder()
                .injectorFactory(new GovernatorInjectorFactory())
                .enableAutoConfig(AUTO_DISCOVERY_EXTENSION_PACKAGES)
                .modules(new CryptoSupportModule(), new CertificateServerModule())
```

However, since upgrade to dropwizard 2 a guicey 5.0.0 (but keeping the same governator 1.17.10),
Suddenly guice is complaining about binding collisions.  Long story short, I can only resolve this by switching to 

```
 this.guiceBundle = GuiceBundle.builder()
                .injectorFactory(new GovernatorInjectorFactory())
                .enableAutoConfig(AUTO_DISCOVERY_EXTENSION_PACKAGES)
                .modules(new CryptoSupportModule())
                .modulesOverride(new CertificateServerModule())
```

This isn't necessarily a bad way to do things, but it does make me question to what extent the governator integration is still worthwhile to me.  Has anything changed in the way guicey enumerates the guice modules it is meant to bind, or is the governator integration not supported in the same way?

N.B. Editing for formatting

**Comment by xvik** [comment]
Yes, its guicey change: since 5.0 [guicey parse all specified modules](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/guice/module-analysis/) before injector creation to be able to detect extensions in guice bindings and be able to disable deep (transitive) guice modules.

You can disable this analysis and after that, everything will work as before:

```java
GuiceBundle.builder()
    .option(GuiceyOptions.AnalyzeModules, false)
```

Of course, after disabling analysis new features (relying on it) will not work, but you are not using them now so it's ok. 

Also, you will not be able to use, [guice report](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/diagnostic/guice-report/) and [aop report](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/diagnostic/aop-report/) because it also parses modules (and will fail)

**Comment by nheitz** [comment]
Wow, excellent response time and quality.  Ok, that eases my mind....and I may pull governator after all.

Quick question...if I chain multiple modules in the "moduleOverride" call, does it fold from the end of the array to the beginning?  Can I rely on the last one specfied to have the ultimate override?

**Comment by xvik** [comment]
In guicey, "no": because guicey works like this: 

```java
Modules.override(all modules from .module()).with(all modules from .moduleOverride())
```

So guice will complain about duplicate bindings within `modulesOverride`.

There is a special [injector factory](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/test/#overriding-overridden-beans) which you can use for 3rd level overrides. 

----

But with governator," yes": [injector factory](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/guice/injector/#injector-factory) will receive modules in order of registration, so [governator transformer](https://github.com/Netflix/governator/blob/master/governator-legacy/src/main/java/com/netflix/governator/guice/transformer/OverrideAllDuplicateBindings.java) will process them in the correct order.

But, you should not use `.modulesOverride` in this case, because if there will be even one overriding module, guicey will pass the result of `Modules.override` into injector factory and so governator will not be able to process modules.

As a side note, this is a very strange problem and governator transformer is a pure hack. If possible, it would be much better to re-organize logic to avoid such overrides at all. I can't imagine how would you track what exact binding works in your application in case of problems.

**Comment by nheitz** [comment]
I completely agree... However, in one particularly odd edge case involving a a kotlin-Java integration, I needed to override the Java library's Jackson object mapper with one that included some nice kotlin extensions. The perils of shared libs. From now, however, my goal is to eliminate both overrides and the use of governator.  

Thank you again.
