### ISSUE TITLE
Config value not injected without explicit name

### ISSUE THREAD

**Issue by gabooh** [xvik/dropwizard-guicey#78]
Given this config value in yml file :

> defaultName: Stranger

And this Configuration class:

```
public class AppConfiguration extends Configuration {

    @NotEmpty
    @JsonProperty
    private String defaultName = "Stranger";
}
```

This code in a resource doesn't work :

```
@Inject
@Config
private String defaultName;
```

I get an exception at app startup :

> 1) No implementation for java.lang.String annotated with @ru.vyarus.dropwizard.guice.module.yaml.bind.Config(value="") was bound.
>   while locating java.lang.String annotated with @ru.vyarus.dropwizard.guice.module.yaml.bind.Config(value="")
>     for field at com.lrb.lrbserve.AppResource.defaultName(AppResource.java:21)
> 

But this code does work :

```
@Inject
@Config("defaultName")
private String defaultName;
```

When using printCustomConfigurationBindings() I have this in the report :

> Configuration paths bindings:
> 
>         AppConfiguration:
>             
>             @Config("defaultName") String = "Stranger"

Reading the documentation about configuration binding, shouldn't the code with a simple @Config work to inject the value ?
This is with guicey 5.0.0 and DW 2.0.1.

**Comment by xvik** [comment]
Imagine if you will have in your configuration:

```java
public class AppConfiguration extends Configuration {

    private String defaultName = "Stranger";
    private String patrickName = "Patrick";
}
```

Both properties are stings. What should be injected in this case?

```java
@Inject
@Config
private String configValue;
```

This is a pure guice binding (target injection field name can't be counted due to the nature of bindings). It's simply impossible to express bindings difference without an additional constant.

Guicey performs uniqueness analysis for sub configuration objects and if you used only one unique sub object in the configuration (it may appear on any level): 

```java
public class  Sub { .. }
public class AppConfiguration extends Configuration {

    private Sub sub;
}
```

you can inject it without path:

```java
@Inject
@Config
private Sub subConfig;
```

String (int, long, etc.) properties will never be unique due to dropwizard base configuration.
`printCustomConfigurationBindings()` shows you only properties of your configuration (hiding dropwizard values), but all bindings were set (including dropwizard `Configuration`). This could be seen on complete guice bindings report. 

I was sure these bindings would confuse, so did report to show exactly what is available. Target bindings may change due to changed property types (e.g. change from Integer to Long will lead different binding) and actual values (entire subtrees may appear or disappear because of values; for example, dropwizard's `server.` path may be quite different depending on implementation used). 

It all might be not easy to predict and only report could show what is really available.

**Comment by gabooh** [comment]
Thank you for your detailed answer!

If I understand correctly, injecting without path is only available for sub configuration (and thus, class object, not strings, ints, etc). I've just tried it and it indeed work.

I thought, as the name was unique, and the config value was properly parsed, that it would work.

Anyway, using an explicit config name is not an issue.

Using guicey has been nice so far, thank you very much.
