### ISSUE TITLE
Dropwizard App does not exit properly if Guice Injection fails

### ISSUE THREAD

**Issue by adamdougal** [xvik/dropwizard-guicey#8]
Hi, 
When injection fails during startup the application doesn't die, but just sits there. I think a System.exit is needed if any exceptions creating the injector occurs. Similar to how dropwizard guice does it: https://github.com/HubSpot/dropwizard-guice/blob/fddd2858df774e10194de2c29459e8cebc59eac3/src/main/java/com/hubspot/dropwizard/guice/GuiceBundle.java#L105-L112

**Comment by henryptung** [comment]
Hm, I must say I don't really agree with this bug report; it overrides the normal exception/error-handling of Dropwizard.  If shutdown-on-initialization-failure was a desired behavior, that should be encoded in Dropwizard itself (to call `System.exit()` on any thrown exception in `initialize()` or `run()`).

For part of why `System.exit()` is so heinous, take a look at this example:

```java
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class TestSystemExit {
    private static class MyThread extends Thread {
        private final Path myJsonFile = Paths.get("test.json");
        @Override
        public void run() {
            boolean success = false;
            try (BufferedWriter writer = Files.newBufferedWriter(myJsonFile)) {
                System.out.println("Starting to write file");
                writer.write('[');
                boolean first = true;
                for (int i = 0; i < 5; i++) {
                    if (first) {
                        first = false;
                    } else {
                        writer.write(',');
                    }
                    writer.write(Integer.toString(i));
                    writer.flush();
                    System.out.println("Wrote " + i + ", taking a break...");
                    Thread.sleep(2000L);
                }
                writer.write(']');
                success = true;
            } catch (IOException | InterruptedException e) {
                System.err.println("Well, something was thrown");
                e.printStackTrace();
            } finally {
                if (success) {
                    System.out.println("Done writing!");
                } else {
                    System.err.println("Oh no! Let's clean up the DB");
                    try {
                        Files.deleteIfExists(myJsonFile);
                    } catch (IOException e) {
                        System.err.println("Failed to delete corrupted file!");
                        e.printStackTrace();
                    }
                }
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new MyThread().start();

        Thread.sleep(5000L);
        System.exit(1);
    }

}
```

In this example, the running thread is terminated, as expected - but the finally block does not run. The currently-running thread is literally killed in place, with no opportunity to catch or clean up. In this example, all we get out of it is a partially written JSON file; but in other circumstances, this could lead to things like stale (distributed) locks or DB corruption, due to lack of cleanup.

`System.exit()` is one of the two things that violate the contract that a `finally` block is always called - the other being an outright crash or memory corruption of the JVM (e.g. segfault). It's a pretty heavy-handed way to take the application down.

@adamdougal, the behavior you're seeing is almost certainly due to something like a thread pool, or something creating dormant threads, alive in the JVM. Unfortunately such threads imply a notion of lifecycle, or at least notice of destruction; there is a _very_ lengthy discussion [here](https://github.com/google/guice/issues/62) on the topic, which ends in a decision not to implement lifecycle management.

Thankfully, Dropwizard does have support for lifecycle management; if you change your bean definition to one like:

```java
public class MyModule extends AbstractModule {
    /* ... */
    @Singleton
    @Provides
    public MyManaged myManaged(Environment environment) {
        MyManaged myManaged = new MyManaged();
        environment.lifecycle().manage(myManaged);
        return myManaged;
    }
}
```

your bean will be started (and stopped) in accordance with the application.  This allows you to defer startup of auxiliary threads to startup of the server itself, and to ensure that such threads are cleanly terminated with the rest of the application.

**Comment by henryptung** [comment]
Actually, in this case, what got me so angry is that `System.exit()` exits _so_ fast and _so_ forcefully, that the previous `logger.error` line doesn't get a chance to print. Thus, you get no stack trace.

Woop.

**Comment by xvik** [comment]
@henryptung I agree that force exit on error is wierd. Personally I never face problems with dropwizard hangs on startup. But the fact that dropwizard-guice used the same trick convienced me that there might be an issue with this in some cases.

Logger issue is a serious problem and probably there might be other side effects. 
The best I can do now is to revert this change. 
If someone need to forcefully call exit, it could still be done using custom injector factory.
 
@adamdougal If you have real-life cases when system exit is really required please tell us

**Comment by adamdougal** [comment]
Having looked a bit deeper into what was happening I think you are correct @henryptung. 

Unfortunately for me having a managed object doesn't seem to fix the problem and I think it may actually be a problem with another library that we are using. For the record, we are using Cassandra, and it's when the driver throws an exception, however even if you close the objects it uses, the process still hangs.

I also assumed that because dropwizard-guice was doing the same thing, it was the correct thing to do and was a bug in dropwizard-guicey.

**Comment by xvik** [comment]
As managed object used for both startup and cleanup, problem moves from injector creation phase to jetty lifecycle event. In this case forcing exit on injector failure will be useless.

Moreover, official guice best practice: modules should be side-effect free (https://github.com/google/guice/wiki/ModulesShouldBeFastAndSideEffectFree)
So using Managed objects must be required. I will look how I can improve docs to mention this point.

And sorry, I shoud have paid more attention to situation overall.

**Comment by henryptung** [comment]
No worries, I only noticed how deep the issue was when I discovered the silenced logs; I'd been aware that `System.exit()` had issues, but not ones this severe.
<sup><sub>
\<\_\<
\>\_\>
Time to clean up that `System.exit()` call I wrote a few weeks ago...
</sub></sup>
